// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID   int    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:varchar(255);not null;uniqueIndex:name,priority:1" json:"name"` // 标签名称
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
