// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserInfo = "user_info"

// UserInfo mapped from table <user_info>
type UserInfo struct {
	ID         int        `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Nickname   *string    `gorm:"column:nickname;type:varchar(128)" json:"nickname"`
	Avatar     *string    `gorm:"column:avatar;type:varchar(128)" json:"avatar"`
	Intro      *string    `gorm:"column:intro;type:varchar(255)" json:"intro"`
	Sex        *uint      `gorm:"column:sex;type:tinyint(3) unsigned zerofill" json:"sex"`
	CreateTime *time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time" example:"2022-11-16T16:00:00.000Z"`
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
