// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/login": {
            "post": {
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bean.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/tag/add": {
            "post": {
                "summary": "标签添加",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Tag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tag/delete": {
            "delete": {
                "summary": "标签删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tag/list/{page}": {
            "get": {
                "summary": "标签查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keywords",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tag/update": {
            "post": {
                "summary": "标签更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "参数",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Tag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/todo/add": {
            "post": {
                "summary": "todo添加",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TodoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/todo/delete": {
            "delete": {
                "summary": "todo删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/todo/list/{page}": {
            "get": {
                "summary": "todo查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/todo/update": {
            "post": {
                "summary": "todo修改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TodoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "description": "用户信息",
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/bean.UserInfoResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/list/{page}": {
            "get": {
                "description": "用户列表",
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.PageResult"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "datas": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/entity.UserInfo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/token/parse": {
            "get": {
                "summary": "用户token信息解析",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录后的token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bean.LoginResp": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/entity.UserInfo"
                },
                "token": {
                    "type": "string",
                    "example": ""
                },
                "uid": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "bean.UserInfoResp": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/entity.UserInfo"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uid": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.AuthReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": ""
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.TodoReq": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Tag"
                    }
                },
                "todo": {
                    "$ref": "#/definitions/entity.Todo"
                }
            }
        },
        "entity.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "标签名称",
                    "type": "string"
                }
            }
        },
        "entity.Todo": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "done": {
                    "description": "完成情况",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "priority": {
                    "description": "优先级",
                    "type": "integer"
                },
                "start_time": {
                    "description": "日期",
                    "type": "string",
                    "example": "2022-11-16T16:00:00.000Z"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "entity.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string",
                    "example": "2022-11-16T16:00:00.000Z"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "sex": {
                    "type": "integer"
                }
            }
        },
        "response.PageResult": {
            "type": "object",
            "properties": {
                "datas": {},
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
